# Generated by Django 3.2 on 2021-05-20 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='model',
            unique_together={('name', 'make')},
        ),
    ]
