# Generated by Django 3.2 on 2021-05-20 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_model_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trim',
            unique_together={('name', 'model')},
        ),
    ]
